use chrono::{DateTime, FixedOffset, Utc};

const UTC8_OFFSET_SECONDS: i32 = 8 * 3600;

pub(super) fn format_utc8_datetime(time: &DateTime<Utc>, fmt: &str) -> String {
    if let Some(offset) = FixedOffset::east_opt(UTC8_OFFSET_SECONDS) {
        return time.with_timezone(&offset).format(fmt).to_string();
    }
    time.format(fmt).to_string()
}

pub(super) fn generated_at_utc8_text() -> String {
    let generated_at = format_utc8_datetime(&Utc::now(), "%Y/%m/%d %H:%M:%S");
    format!("Generated by Phi-Backend at {generated_at} UTC+8")
}

pub(super) fn updated_at_utc_text(time: &DateTime<Utc>, fmt: &str) -> String {
    format!("Updated at {} UTC", time.format(fmt))
}
